#!/usr/bin/env python3
"""Generate src/gen3/generated/observer_tables.h from pybattle/data/game_data.json.

The C++ observer / encoder (src/gen3/observer.cpp) reads the game's own tables (gSpeciesInfo, gBattleMoves,
gItems, gTypeEffectiveness) from the compiled decomp. What only the JSON holds is generated here, so the C++ side
never parses JSON: the vocabulary sizes of the encoding (rl/gamedata.py), stat stage ratios, the Factory's fixed IV
table (static in battle_factory.c) and the ids behind the names the Python code uses (ABILITY_*, EFFECT_*,
HOLD_EFFECT_*, TYPE_*, MOVE_*, SPECIES_*).

Usage: gen_observer_tables.py [--check]
"""

import argparse
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "pybattle", "data", "game_data.json")
OUT = os.path.join(REPO, "src", "gen3", "generated", "observer_tables.h")

# rl/damage.py TYPE_POWER_ITEM: HOLD_EFFECT_<T>_POWER -> type index (TYPE_MYSTERY has none)
POWER_TYPES = ("NORMAL", "FIGHTING", "FLYING", "POISON", "GROUND", "ROCK", "BUG", "GHOST", "STEEL", None, "FIRE",
               "WATER", "GRASS", "ELECTRIC", "PSYCHIC", "ICE", "DRAGON", "DARK")


def names(d, table, prefix):
    out, used = [], set()
    for k, v in sorted(d["names"][table].items(), key=lambda kv: int(kv[0])):
        if not v.startswith(prefix):
            continue
        n = v[len(prefix):]
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", n) or n in used:
            continue
        used.add(n)
        out.append((n, int(k)))
    return out


def generate():
    d = json.load(open(SRC))
    c = d["counts"]
    L = ["// GENERATED by scripts/gen_observer_tables.py from pybattle/data/game_data.json. Do not edit.",
         "#pragma once", "", "namespace pkmn {", "namespace obsgen {", ""]
    L.append(f"constexpr int N_SPECIES = {len(d['species'])};")
    L.append(f"constexpr int N_MOVES = {len(d['moves'])};")
    L.append(f"constexpr int N_ITEMS = {c['ITEMS_COUNT']};")
    L.append(f"constexpr int N_ITEMS_TABLE = {len(d['items'])};")
    L.append(f"constexpr int N_ABILITIES = {c['ABILITIES_COUNT']};")
    L.append(f"constexpr int N_EFFECTS = {c['NUM_BATTLE_MOVE_EFFECTS']};")
    L.append("constexpr int N_TYPES = 18;")
    L.append("")
    r = d["stat_stage_ratios"]
    L.append(f"constexpr int STAT_STAGE_RATIOS[{len(r)}][2] = {{" + ", ".join(f"{{{a}, {b}}}" for a, b in r) + "};")
    iv = d["factory_fixed_ivs"]
    L.append(f"constexpr int N_FIXED_IV_ROWS = {len(iv)};")
    L.append(f"constexpr int FACTORY_FIXED_IVS[{len(iv)}][2] = {{" + ", ".join(f"{{{a}, {b}}}" for a, b in iv) + "};")
    L.append("")
    for ns, table, prefix in (("ability", "abilities", "ABILITY_"), ("effect", "effects", "EFFECT_"),
                              ("hold", "hold_effects", "HOLD_EFFECT_"), ("type", "types", "TYPE_"),
                              ("move", "moves", "MOVE_"), ("species", "species", "SPECIES_")):
        L.append(f"namespace {ns} {{")
        for n, v in names(d, table, prefix):
            L.append(f"constexpr int {n} = {v};")
        L.append(f"}}  // namespace {ns}")
        L.append("")
    hold = dict((n, v) for n, v in names(d, "hold_effects", "HOLD_EFFECT_"))
    pairs = [(hold[f"{t}_POWER"], i) for i, t in enumerate(POWER_TYPES) if t]
    L.append(f"constexpr int N_TYPE_POWER_ITEMS = {len(pairs)};")
    L.append(f"constexpr int TYPE_POWER_ITEMS[{len(pairs)}][2] = {{  // hold effect, type")
    L.append("    " + ", ".join(f"{{{h}, {t}}}" for h, t in pairs) + "};")
    L += ["", "}  // namespace obsgen", "}  // namespace pkmn", ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the generated header is out of date")
    args = ap.parse_args()
    text = generate()
    if args.check:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print(f"{OUT} is out of date: run scripts/gen_observer_tables.py")
            sys.exit(1)
        return
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
