#!/usr/bin/env python3
"""Generate no-op definitions for everything the vendored battle code references but the
host build does not implement (graphics, sound, text windows, link cable, save file...).

Signatures come from the decomp's own declarations, so stubs have the right types.
Functions return zero, except "is it finished/done?" queries, which return TRUE so the
battle code never waits on an animation or sound that does not exist. Data symbols become
zero-filled storage; text becomes an empty (EOS-terminated) string.

Usage: gen_stubs.py <undefined-symbols.txt>    (writes src/gen3/generated/stubs.c)

The build (CMake) produces the undefined list; see src/gen3/CMakeLists.txt.
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR = os.path.join(REPO, "third_party", "pokeemerald")
OUT = os.path.join(REPO, "src", "gen3", "generated", "stubs.c")

# Implemented by hand in src/gen3/host.c or provided by libc / the linker.
NOT_STUBBED = {"memcpy", "memset", "memcmp", "strlen", "abort", "_GLOBAL_OFFSET_TABLE_", "__stack_chk_fail",
               "__start_gen3_ram", "__stop_gen3_ram", "Gen3_ResolveAddress",
               # palette fades: emulated in src/gen3/host.c (battle code waits on them)
               "BeginNormalPaletteFade", "BeginFastPaletteFade", "UpdatePaletteFade", "ResetPaletteFade",
               "ResetPaletteFadeControl", "gPaletteFade"}

LIBC = {"dladdr", "stderr", "stdout", "fprintf", "printf", "puts", "malloc", "calloc", "free", "memmove", "strcmp", "strcpy"}

# Queries that must answer "yes, finished" for the battle flow to advance.
RETURN_TRUE = re.compile(r"^(Is\w*(Finished|Done|Complete)\w*|IsCryFinished|BattleInitAllSprites|LoadChosenBattleElement)$")

HEADER_ORDER = []


def load_declarations():
    """name -> ('func', ret, args) | ('data', type, suffix)"""
    decls = {}
    paths = []
    for root, _, files in os.walk(os.path.join(VENDOR, "include")):
        paths += [os.path.join(root, f) for f in files if f.endswith(".h")]
    for fname in os.listdir(os.path.join(VENDOR, "src")):
        if fname.endswith(".c"):
            paths.append(os.path.join(VENDOR, "src", fname))
    func = re.compile(r"(?:^|;|\})\s*((?:const\s+|unsigned\s+|signed\s+|struct\s+|enum\s+|static\s+)*\w+[\s\*]+)(\w+)\s*\(([^;{}()]*(?:\([^()]*\)[^;{}()]*)*)\)\s*;",
                      re.M)
    data_in_c = {}
    data = re.compile(r"^\s*extern\s+((?:const\s+|struct\s+|enum\s+|unsigned\s+|signed\s+)*\w+(?:\s+const)?[\s\*]*(?:const\s*)?)(\w+)((?:\s*\[[^\]]*\])*)\s*;", re.M)
    fptr = re.compile(r"^\s*extern\s+(.*\(\s*\*\s*(\w+)\s*(\[[^\]]*\])?\s*\)\s*\(.*\))\s*;", re.M)
    for path in paths:
        text = re.sub(r"/\*.*?\*/", "", open(path, errors="replace").read(), flags=re.S)
        text = re.sub(r"//[^\n]*", "", text)
        for m in fptr.finditer(text):
            decls.setdefault(m.group(2), ("fptr", m.group(1), ""))
        for m in data.finditer(text):
            decls.setdefault(m.group(2), ("data", m.group(1).strip(), m.group(3).strip()))
            if path.endswith(".c"):
                data_in_c.setdefault(m.group(2), m.group(0).strip())
        for m in func.finditer(text):
            ret, name, args = m.group(1).strip(), m.group(2), " ".join(m.group(3).split())
            if ret.startswith("static") or name in ("if", "while", "for", "switch", "return", "sizeof"):
                continue
            decls.setdefault(name, ("func", ret, args))
    decls["__data_in_c__"] = data_in_c
    return decls


def stub_function(name, ret, args):
    if not args:
        args = "void"
    if ret == "void":
        body = ""
    elif RETURN_TRUE.match(name):
        body = " return TRUE;"
    elif ret.startswith("struct") and "*" not in ret:
        body = f" {ret} r; memset(&r, 0, sizeof(r)); return r;"
    else:
        body = f" return ({ret})0;"
    return f"{ret} {name}({args}) {{{body} }}"


def stub_data(name, typ, suffix):
    base = typ.replace("const", "").strip()
    is_text = base in ("u8", "char") and suffix
    if suffix.startswith("[]"):
        suffix = "[256]" + suffix[2:]
    if is_text:
        # empty string: EOS (0xFF) so string routines terminate
        return f"{typ} {name}{suffix} = {{0xFF}};"
    return f"{typ} {name}{suffix};"


def main():
    undefined = [l.strip() for l in open(sys.argv[1]) if l.strip()]
    decls = load_declarations()
    out = ["// GENERATED by scripts/gen_stubs.py. Do not edit.",
           "// No-op stand-ins for the parts of the game the headless battle core does not need.",
           '#include "global.h"']
    headers = set()
    for fname in os.listdir(os.path.join(VENDOR, "src")):
        if fname.endswith(".c"):
            headers.update(re.findall(r'^#include "([^"]+\.h)"', open(os.path.join(VENDOR, "src", fname)).read(), re.M))
    out += [f'#include "{h}"' for h in sorted(headers) if not h.startswith("data/") and h != "global.h"]
    out += ["#include <string.h>", ""]
    unknown = []
    data_in_c = decls.pop("__data_in_c__")
    undefined = [n for n in undefined if not n.startswith("__") and n not in LIBC and not n.startswith("gGen3")]
    out += [data_in_c[n] for n in sorted(set(undefined) - NOT_STUBBED) if n in data_in_c]
    out.append("")
    undefined = [n for n in undefined if not n.startswith("__") and n not in LIBC and not n.startswith("gGen3")]
    for name in sorted(set(undefined) - NOT_STUBBED):
        d = decls.get(name)
        if d is None:
            # Declared in a way the parser does not understand: let the compiler supply the type.
            unknown.append(name)
            out.append(f"__typeof__({name}) {name};")
        elif d[0] == "func":
            out.append(stub_function(name, d[1], d[2]))
        elif d[0] == "fptr":
            out.append(f"{d[1]};")
        elif d[2].startswith("[]"):
            out.append(stub_data(name, d[1], d[2]))
        else:
            out.append(f"__typeof__({name}) {name};")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write("\n".join(out) + "\n")
    print(f"{len(set(undefined) - NOT_STUBBED)} stubs ({len(unknown)} without declaration)")
    if unknown:
        print("  undeclared:", " ".join(unknown[:40]), "..." if len(unknown) > 40 else "")


if __name__ == "__main__":
    main()
