#pragma once

#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif

#include <cstdint>

namespace pkmn {

enum : uint16_t {
    SPECIES_NONE = 0,
    SPECIES_BULBASAUR = 1,
    SPECIES_IVYSAUR = 2,
    SPECIES_VENUSAUR = 3,
    SPECIES_CHARMANDER = 4,
    SPECIES_CHARMELEON = 5,
    SPECIES_CHARIZARD = 6,
    SPECIES_SQUIRTLE = 7,
    SPECIES_WARTORTLE = 8,
    SPECIES_BLASTOISE = 9,
    SPECIES_CATERPIE = 10,
    SPECIES_METAPOD = 11,
    SPECIES_BUTTERFREE = 12,
    SPECIES_WEEDLE = 13,
    SPECIES_KAKUNA = 14,
    SPECIES_BEEDRILL = 15,
    SPECIES_PIDGEY = 16,
    SPECIES_PIDGEOTTO = 17,
    SPECIES_PIDGEOT = 18,
    SPECIES_RATTATA = 19,
    SPECIES_RATICATE = 20,
    SPECIES_SPEAROW = 21,
    SPECIES_FEAROW = 22,
    SPECIES_EKANS = 23,
    SPECIES_ARBOK = 24,
    SPECIES_PIKACHU = 25,
    SPECIES_RAICHU = 26,
    SPECIES_SANDSHREW = 27,
    SPECIES_SANDSLASH = 28,
    SPECIES_NIDORAN_F = 29,
    SPECIES_NIDORINA = 30,
    SPECIES_NIDOQUEEN = 31,
    SPECIES_NIDORAN_M = 32,
    SPECIES_NIDORINO = 33,
    SPECIES_NIDOKING = 34,
    SPECIES_CLEFAIRY = 35,
    SPECIES_CLEFABLE = 36,
    SPECIES_VULPIX = 37,
    SPECIES_NINETALES = 38,
    SPECIES_JIGGLYPUFF = 39,
    SPECIES_WIGGLYTUFF = 40,
    SPECIES_ZUBAT = 41,
    SPECIES_GOLBAT = 42,
    SPECIES_ODDISH = 43,
    SPECIES_GLOOM = 44,
    SPECIES_VILEPLUME = 45,
    SPECIES_PARAS = 46,
    SPECIES_PARASECT = 47,
    SPECIES_VENONAT = 48,
    SPECIES_VENOMOTH = 49,
    SPECIES_DIGLETT = 50,
    SPECIES_DUGTRIO = 51,
    SPECIES_MEOWTH = 52,
    SPECIES_PERSIAN = 53,
    SPECIES_PSYDUCK = 54,
    SPECIES_GOLDUCK = 55,
    SPECIES_MANKEY = 56,
    SPECIES_PRIMEAPE = 57,
    SPECIES_GROWLITHE = 58,
    SPECIES_ARCANINE = 59,
    SPECIES_POLIWAG = 60,
    SPECIES_POLIWHIRL = 61,
    SPECIES_POLIWRATH = 62,
    SPECIES_ABRA = 63,
    SPECIES_KADABRA = 64,
    SPECIES_ALAKAZAM = 65,
    SPECIES_MACHOP = 66,
    SPECIES_MACHOKE = 67,
    SPECIES_MACHAMP = 68,
    SPECIES_BELLSPROUT = 69,
    SPECIES_WEEPINBELL = 70,
    SPECIES_VICTREEBEL = 71,
    SPECIES_TENTACOOL = 72,
    SPECIES_TENTACRUEL = 73,
    SPECIES_GEODUDE = 74,
    SPECIES_GRAVELER = 75,
    SPECIES_GOLEM = 76,
    SPECIES_PONYTA = 77,
    SPECIES_RAPIDASH = 78,
    SPECIES_SLOWPOKE = 79,
    SPECIES_SLOWBRO = 80,
    SPECIES_MAGNEMITE = 81,
    SPECIES_MAGNETON = 82,
    SPECIES_FARFETCHD = 83,
    SPECIES_DODUO = 84,
    SPECIES_DODRIO = 85,
    SPECIES_SEEL = 86,
    SPECIES_DEWGONG = 87,
    SPECIES_GRIMER = 88,
    SPECIES_MUK = 89,
    SPECIES_SHELLDER = 90,
    SPECIES_CLOYSTER = 91,
    SPECIES_GASTLY = 92,
    SPECIES_HAUNTER = 93,
    SPECIES_GENGAR = 94,
    SPECIES_ONIX = 95,
    SPECIES_DROWZEE = 96,
    SPECIES_HYPNO = 97,
    SPECIES_KRABBY = 98,
    SPECIES_KINGLER = 99,
    SPECIES_VOLTORB = 100,
    SPECIES_ELECTRODE = 101,
    SPECIES_EXEGGCUTE = 102,
    SPECIES_EXEGGUTOR = 103,
    SPECIES_CUBONE = 104,
    SPECIES_MAROWAK = 105,
    SPECIES_HITMONLEE = 106,
    SPECIES_HITMONCHAN = 107,
    SPECIES_LICKITUNG = 108,
    SPECIES_KOFFING = 109,
    SPECIES_WEEZING = 110,
    SPECIES_RHYHORN = 111,
    SPECIES_RHYDON = 112,
    SPECIES_CHANSEY = 113,
    SPECIES_TANGELA = 114,
    SPECIES_KANGASKHAN = 115,
    SPECIES_HORSEA = 116,
    SPECIES_SEADRA = 117,
    SPECIES_GOLDEEN = 118,
    SPECIES_SEAKING = 119,
    SPECIES_STARYU = 120,
    SPECIES_STARMIE = 121,
    SPECIES_MR_MIME = 122,
    SPECIES_SCYTHER = 123,
    SPECIES_JYNX = 124,
    SPECIES_ELECTABUZZ = 125,
    SPECIES_MAGMAR = 126,
    SPECIES_PINSIR = 127,
    SPECIES_TAUROS = 128,
    SPECIES_MAGIKARP = 129,
    SPECIES_GYARADOS = 130,
    SPECIES_LAPRAS = 131,
    SPECIES_DITTO = 132,
    SPECIES_EEVEE = 133,
    SPECIES_VAPOREON = 134,
    SPECIES_JOLTEON = 135,
    SPECIES_FLAREON = 136,
    SPECIES_PORYGON = 137,
    SPECIES_OMANYTE = 138,
    SPECIES_OMASTAR = 139,
    SPECIES_KABUTO = 140,
    SPECIES_KABUTOPS = 141,
    SPECIES_AERODACTYL = 142,
    SPECIES_SNORLAX = 143,
    SPECIES_ARTICUNO = 144,
    SPECIES_ZAPDOS = 145,
    SPECIES_MOLTRES = 146,
    SPECIES_DRATINI = 147,
    SPECIES_DRAGONAIR = 148,
    SPECIES_DRAGONITE = 149,
    SPECIES_MEWTWO = 150,
    SPECIES_MEW = 151,
    SPECIES_CHIKORITA = 152,
    SPECIES_BAYLEEF = 153,
    SPECIES_MEGANIUM = 154,
    SPECIES_CYNDAQUIL = 155,
    SPECIES_QUILAVA = 156,
    SPECIES_TYPHLOSION = 157,
    SPECIES_TOTODILE = 158,
    SPECIES_CROCONAW = 159,
    SPECIES_FERALIGATR = 160,
    SPECIES_SENTRET = 161,
    SPECIES_FURRET = 162,
    SPECIES_HOOTHOOT = 163,
    SPECIES_NOCTOWL = 164,
    SPECIES_LEDYBA = 165,
    SPECIES_LEDIAN = 166,
    SPECIES_SPINARAK = 167,
    SPECIES_ARIADOS = 168,
    SPECIES_CROBAT = 169,
    SPECIES_CHINCHOU = 170,
    SPECIES_LANTURN = 171,
    SPECIES_PICHU = 172,
    SPECIES_CLEFFA = 173,
    SPECIES_IGGLYBUFF = 174,
    SPECIES_TOGEPI = 175,
    SPECIES_TOGETIC = 176,
    SPECIES_NATU = 177,
    SPECIES_XATU = 178,
    SPECIES_MAREEP = 179,
    SPECIES_FLAAFFY = 180,
    SPECIES_AMPHAROS = 181,
    SPECIES_BELLOSSOM = 182,
    SPECIES_MARILL = 183,
    SPECIES_AZUMARILL = 184,
    SPECIES_SUDOWOODO = 185,
    SPECIES_POLITOED = 186,
    SPECIES_HOPPIP = 187,
    SPECIES_SKIPLOOM = 188,
    SPECIES_JUMPLUFF = 189,
    SPECIES_AIPOM = 190,
    SPECIES_SUNKERN = 191,
    SPECIES_SUNFLORA = 192,
    SPECIES_YANMA = 193,
    SPECIES_WOOPER = 194,
    SPECIES_QUAGSIRE = 195,
    SPECIES_ESPEON = 196,
    SPECIES_UMBREON = 197,
    SPECIES_MURKROW = 198,
    SPECIES_SLOWKING = 199,
    SPECIES_MISDREAVUS = 200,
    SPECIES_UNOWN = 201,
    SPECIES_WOBBUFFET = 202,
    SPECIES_GIRAFARIG = 203,
    SPECIES_PINECO = 204,
    SPECIES_FORRETRESS = 205,
    SPECIES_DUNSPARCE = 206,
    SPECIES_GLIGAR = 207,
    SPECIES_STEELIX = 208,
    SPECIES_SNUBBULL = 209,
    SPECIES_GRANBULL = 210,
    SPECIES_QWILFISH = 211,
    SPECIES_SCIZOR = 212,
    SPECIES_SHUCKLE = 213,
    SPECIES_HERACROSS = 214,
    SPECIES_SNEASEL = 215,
    SPECIES_TEDDIURSA = 216,
    SPECIES_URSARING = 217,
    SPECIES_SLUGMA = 218,
    SPECIES_MAGCARGO = 219,
    SPECIES_SWINUB = 220,
    SPECIES_PILOSWINE = 221,
    SPECIES_CORSOLA = 222,
    SPECIES_REMORAID = 223,
    SPECIES_OCTILLERY = 224,
    SPECIES_DELIBIRD = 225,
    SPECIES_MANTINE = 226,
    SPECIES_SKARMORY = 227,
    SPECIES_HOUNDOUR = 228,
    SPECIES_HOUNDOOM = 229,
    SPECIES_KINGDRA = 230,
    SPECIES_PHANPY = 231,
    SPECIES_DONPHAN = 232,
    SPECIES_PORYGON2 = 233,
    SPECIES_STANTLER = 234,
    SPECIES_SMEARGLE = 235,
    SPECIES_TYROGUE = 236,
    SPECIES_HITMONTOP = 237,
    SPECIES_SMOOCHUM = 238,
    SPECIES_ELEKID = 239,
    SPECIES_MAGBY = 240,
    SPECIES_MILTANK = 241,
    SPECIES_BLISSEY = 242,
    SPECIES_RAIKOU = 243,
    SPECIES_ENTEI = 244,
    SPECIES_SUICUNE = 245,
    SPECIES_LARVITAR = 246,
    SPECIES_PUPITAR = 247,
    SPECIES_TYRANITAR = 248,
    SPECIES_LUGIA = 249,
    SPECIES_HO_OH = 250,
    SPECIES_CELEBI = 251,
    SPECIES_TREECKO = 252,
    SPECIES_GROVYLE = 253,
    SPECIES_SCEPTILE = 254,
    SPECIES_TORCHIC = 255,
    SPECIES_COMBUSKEN = 256,
    SPECIES_BLAZIKEN = 257,
    SPECIES_MUDKIP = 258,
    SPECIES_MARSHTOMP = 259,
    SPECIES_SWAMPERT = 260,
    SPECIES_POOCHYENA = 261,
    SPECIES_MIGHTYENA = 262,
    SPECIES_ZIGZAGOON = 263,
    SPECIES_LINOONE = 264,
    SPECIES_WURMPLE = 265,
    SPECIES_SILCOON = 266,
    SPECIES_BEAUTIFLY = 267,
    SPECIES_CASCOON = 268,
    SPECIES_DUSTOX = 269,
    SPECIES_LOTAD = 270,
    SPECIES_LOMBRE = 271,
    SPECIES_LUDICOLO = 272,
    SPECIES_SEEDOT = 273,
    SPECIES_NUZLEAF = 274,
    SPECIES_SHIFTRY = 275,
    SPECIES_NINCADA = 276,
    SPECIES_NINJASK = 277,
    SPECIES_SHEDINJA = 278,
    SPECIES_TAILLOW = 279,
    SPECIES_SWELLOW = 280,
    SPECIES_SHROOMISH = 281,
    SPECIES_BRELOOM = 282,
    SPECIES_SPINDA = 283,
    SPECIES_WINGULL = 284,
    SPECIES_PELIPPER = 285,
    SPECIES_SURSKIT = 286,
    SPECIES_MASQUERAIN = 287,
    SPECIES_WAILMER = 288,
    SPECIES_WAILORD = 289,
    SPECIES_SKITTY = 290,
    SPECIES_DELCATTY = 291,
    SPECIES_KECLEON = 292,
    SPECIES_BALTOY = 293,
    SPECIES_CLAYDOL = 294,
    SPECIES_NOSEPASS = 295,
    SPECIES_TORKOAL = 296,
    SPECIES_SABLEYE = 297,
    SPECIES_BARBOACH = 298,
    SPECIES_WHISCASH = 299,
    SPECIES_LUVDISC = 300,
    SPECIES_CORPHISH = 301,
    SPECIES_CRAWDAUNT = 302,
    SPECIES_FEEBAS = 303,
    SPECIES_MILOTIC = 304,
    SPECIES_CARVANHA = 305,
    SPECIES_SHARPEDO = 306,
    SPECIES_TRAPINCH = 307,
    SPECIES_VIBRAVA = 308,
    SPECIES_FLYGON = 309,
    SPECIES_MAKUHITA = 310,
    SPECIES_HARIYAMA = 311,
    SPECIES_ELECTRIKE = 312,
    SPECIES_MANECTRIC = 313,
    SPECIES_NUMEL = 314,
    SPECIES_CAMERUPT = 315,
    SPECIES_SPHEAL = 316,
    SPECIES_SEALEO = 317,
    SPECIES_WALREIN = 318,
    SPECIES_CACNEA = 319,
    SPECIES_CACTURNE = 320,
    SPECIES_SNORUNT = 321,
    SPECIES_GLALIE = 322,
    SPECIES_LUNATONE = 323,
    SPECIES_SOLROCK = 324,
    SPECIES_AZURILL = 325,
    SPECIES_SPOINK = 326,
    SPECIES_GRUMPIG = 327,
    SPECIES_PLUSLE = 328,
    SPECIES_MINUN = 329,
    SPECIES_MAWILE = 330,
    SPECIES_MEDITITE = 331,
    SPECIES_MEDICHAM = 332,
    SPECIES_SWABLU = 333,
    SPECIES_ALTARIA = 334,
    SPECIES_WYNAUT = 335,
    SPECIES_DUSKULL = 336,
    SPECIES_DUSCLOPS = 337,
    SPECIES_ROSELIA = 338,
    SPECIES_SLAKOTH = 339,
    SPECIES_VIGOROTH = 340,
    SPECIES_SLAKING = 341,
    SPECIES_GULPIN = 342,
    SPECIES_SWALOT = 343,
    SPECIES_TROPIUS = 344,
    SPECIES_WHISMUR = 345,
    SPECIES_LOUDRED = 346,
    SPECIES_EXPLOUD = 347,
    SPECIES_CLAMPERL = 348,
    SPECIES_HUNTAIL = 349,
    SPECIES_GOREBYSS = 350,
    SPECIES_ABSOL = 351,
    SPECIES_SHUPPET = 352,
    SPECIES_BANETTE = 353,
    SPECIES_SEVIPER = 354,
    SPECIES_ZANGOOSE = 355,
    SPECIES_RELICANTH = 356,
    SPECIES_ARON = 357,
    SPECIES_LAIRON = 358,
    SPECIES_AGGRON = 359,
    SPECIES_CASTFORM = 360,
    SPECIES_VOLBEAT = 361,
    SPECIES_ILLUMISE = 362,
    SPECIES_LILEEP = 363,
    SPECIES_CRADILY = 364,
    SPECIES_ANORITH = 365,
    SPECIES_ARMALDO = 366,
    SPECIES_RALTS = 367,
    SPECIES_KIRLIA = 368,
    SPECIES_GARDEVOIR = 369,
    SPECIES_BAGON = 370,
    SPECIES_SHELGON = 371,
    SPECIES_SALAMENCE = 372,
    SPECIES_BELDUM = 373,
    SPECIES_METANG = 374,
    SPECIES_METAGROSS = 375,
    SPECIES_REGIROCK = 376,
    SPECIES_REGICE = 377,
    SPECIES_REGISTEEL = 378,
    SPECIES_KYOGRE = 379,
    SPECIES_GROUDON = 380,
    SPECIES_RAYQUAZA = 381,
    SPECIES_LATIAS = 382,
    SPECIES_LATIOS = 383,
    SPECIES_JIRACHI = 384,
    SPECIES_DEOXYS = 385,
    SPECIES_CHIMECHO = 386,
    SPECIES_COUNT = 387
};

enum : uint16_t {
    MOVE_NONE = 0,
    MOVE_POUND = 1,
    MOVE_KARATE_CHOP = 2,
    MOVE_DOUBLE_SLAP = 3,
    MOVE_COMET_PUNCH = 4,
    MOVE_MEGA_PUNCH = 5,
    MOVE_PAY_DAY = 6,
    MOVE_FIRE_PUNCH = 7,
    MOVE_ICE_PUNCH = 8,
    MOVE_THUNDER_PUNCH = 9,
    MOVE_SCRATCH = 10,
    MOVE_VICE_GRIP = 11,
    MOVE_GUILLOTINE = 12,
    MOVE_RAZOR_WIND = 13,
    MOVE_SWORDS_DANCE = 14,
    MOVE_CUT = 15,
    MOVE_GUST = 16,
    MOVE_WING_ATTACK = 17,
    MOVE_WHIRLWIND = 18,
    MOVE_FLY = 19,
    MOVE_BIND = 20,
    MOVE_SLAM = 21,
    MOVE_VINE_WHIP = 22,
    MOVE_STOMP = 23,
    MOVE_DOUBLE_KICK = 24,
    MOVE_MEGA_KICK = 25,
    MOVE_JUMP_KICK = 26,
    MOVE_ROLLING_KICK = 27,
    MOVE_SAND_ATTACK = 28,
    MOVE_HEADBUTT = 29,
    MOVE_HORN_ATTACK = 30,
    MOVE_FURY_ATTACK = 31,
    MOVE_HORN_DRILL = 32,
    MOVE_TACKLE = 33,
    MOVE_BODY_SLAM = 34,
    MOVE_WRAP = 35,
    MOVE_TAKE_DOWN = 36,
    MOVE_THRASH = 37,
    MOVE_DOUBLE_EDGE = 38,
    MOVE_TAIL_WHIP = 39,
    MOVE_POISON_STING = 40,
    MOVE_TWINEEDLE = 41,
    MOVE_PIN_MISSILE = 42,
    MOVE_LEER = 43,
    MOVE_BITE = 44,
    MOVE_GROWL = 45,
    MOVE_ROAR = 46,
    MOVE_SING = 47,
    MOVE_SUPERSONIC = 48,
    MOVE_SONIC_BOOM = 49,
    MOVE_DISABLE = 50,
    MOVE_ACID = 51,
    MOVE_EMBER = 52,
    MOVE_FLAMETHROWER = 53,
    MOVE_MIST = 54,
    MOVE_WATER_GUN = 55,
    MOVE_HYDRO_PUMP = 56,
    MOVE_SURF = 57,
    MOVE_ICE_BEAM = 58,
    MOVE_BLIZZARD = 59,
    MOVE_PSYBEAM = 60,
    MOVE_BUBBLE_BEAM = 61,
    MOVE_AURORA_BEAM = 62,
    MOVE_HYPER_BEAM = 63,
    MOVE_PECK = 64,
    MOVE_DRILL_PECK = 65,
    MOVE_SUBMISSION = 66,
    MOVE_LOW_KICK = 67,
    MOVE_COUNTER = 68,
    MOVE_SEISMIC_TOSS = 69,
    MOVE_STRENGTH = 70,
    MOVE_ABSORB = 71,
    MOVE_MEGA_DRAIN = 72,
    MOVE_LEECH_SEED = 73,
    MOVE_GROWTH = 74,
    MOVE_RAZOR_LEAF = 75,
    MOVE_SOLAR_BEAM = 76,
    MOVE_POISON_POWDER = 77,
    MOVE_STUN_SPORE = 78,
    MOVE_SLEEP_POWDER = 79,
    MOVE_PETAL_DANCE = 80,
    MOVE_STRING_SHOT = 81,
    MOVE_DRAGON_RAGE = 82,
    MOVE_FIRE_SPIN = 83,
    MOVE_THUNDER_SHOCK = 84,
    MOVE_THUNDERBOLT = 85,
    MOVE_THUNDER_WAVE = 86,
    MOVE_THUNDER = 87,
    MOVE_ROCK_THROW = 88,
    MOVE_EARTHQUAKE = 89,
    MOVE_FISSURE = 90,
    MOVE_DIG = 91,
    MOVE_TOXIC = 92,
    MOVE_CONFUSION = 93,
    MOVE_PSYCHIC = 94,
    MOVE_HYPNOSIS = 95,
    MOVE_MEDITATE = 96,
    MOVE_AGILITY = 97,
    MOVE_QUICK_ATTACK = 98,
    MOVE_RAGE = 99,
    MOVE_TELEPORT = 100,
    MOVE_NIGHT_SHADE = 101,
    MOVE_MIMIC = 102,
    MOVE_SCREECH = 103,
    MOVE_DOUBLE_TEAM = 104,
    MOVE_RECOVER = 105,
    MOVE_HARDEN = 106,
    MOVE_MINIMIZE = 107,
    MOVE_SMOKESCREEN = 108,
    MOVE_CONFUSE_RAY = 109,
    MOVE_WITHDRAW = 110,
    MOVE_DEFENSE_CURL = 111,
    MOVE_BARRIER = 112,
    MOVE_LIGHT_SCREEN = 113,
    MOVE_HAZE = 114,
    MOVE_REFLECT = 115,
    MOVE_FOCUS_ENERGY = 116,
    MOVE_BIDE = 117,
    MOVE_METRONOME = 118,
    MOVE_MIRROR_MOVE = 119,
    MOVE_SELF_DESTRUCT = 120,
    MOVE_EGG_BOMB = 121,
    MOVE_LICK = 122,
    MOVE_SMOG = 123,
    MOVE_SLUDGE = 124,
    MOVE_BONE_CLUB = 125,
    MOVE_FIRE_BLAST = 126,
    MOVE_WATERFALL = 127,
    MOVE_CLAMP = 128,
    MOVE_SWIFT = 129,
    MOVE_SKULL_BASH = 130,
    MOVE_SPIKE_CANNON = 131,
    MOVE_CONSTRICT = 132,
    MOVE_AMNESIA = 133,
    MOVE_KINESIS = 134,
    MOVE_SOFT_BOILED = 135,
    MOVE_HI_JUMP_KICK = 136,
    MOVE_GLARE = 137,
    MOVE_DREAM_EATER = 138,
    MOVE_POISON_GAS = 139,
    MOVE_BARRAGE = 140,
    MOVE_LEECH_LIFE = 141,
    MOVE_LOVELY_KISS = 142,
    MOVE_SKY_ATTACK = 143,
    MOVE_TRANSFORM = 144,
    MOVE_BUBBLE = 145,
    MOVE_DIZZY_PUNCH = 146,
    MOVE_SPORE = 147,
    MOVE_FLASH = 148,
    MOVE_PSYWAVE = 149,
    MOVE_SPLASH = 150,
    MOVE_ACID_ARMOR = 151,
    MOVE_CRABHAMMER = 152,
    MOVE_EXPLOSION = 153,
    MOVE_FURY_SWIPES = 154,
    MOVE_BONEMERANG = 155,
    MOVE_REST = 156,
    MOVE_ROCK_SLIDE = 157,
    MOVE_HYPER_FANG = 158,
    MOVE_SHARPEN = 159,
    MOVE_CONVERSION = 160,
    MOVE_TRI_ATTACK = 161,
    MOVE_SUPER_FANG = 162,
    MOVE_SLASH = 163,
    MOVE_SUBSTITUTE = 164,
    MOVE_STRUGGLE = 165,
    MOVE_SKETCH = 166,
    MOVE_TRIPLE_KICK = 167,
    MOVE_THIEF = 168,
    MOVE_SPIDER_WEB = 169,
    MOVE_MIND_READER = 170,
    MOVE_NIGHTMARE = 171,
    MOVE_FLAME_WHEEL = 172,
    MOVE_SNORE = 173,
    MOVE_CURSE = 174,
    MOVE_FLAIL = 175,
    MOVE_CONVERSION_2 = 176,
    MOVE_AEROBLAST = 177,
    MOVE_COTTON_SPORE = 178,
    MOVE_REVERSAL = 179,
    MOVE_SPITE = 180,
    MOVE_POWDER_SNOW = 181,
    MOVE_PROTECT = 182,
    MOVE_MACH_PUNCH = 183,
    MOVE_SCARY_FACE = 184,
    MOVE_FAINT_ATTACK = 185,
    MOVE_SWEET_KISS = 186,
    MOVE_BELLY_DRUM = 187,
    MOVE_SLUDGE_BOMB = 188,
    MOVE_MUD_SLAP = 189,
    MOVE_OCTAZOOKA = 190,
    MOVE_SPIKES = 191,
    MOVE_ZAP_CANNON = 192,
    MOVE_FORESIGHT = 193,
    MOVE_DESTINY_BOND = 194,
    MOVE_PERISH_SONG = 195,
    MOVE_ICY_WIND = 196,
    MOVE_DETECT = 197,
    MOVE_BONE_RUSH = 198,
    MOVE_LOCK_ON = 199,
    MOVE_OUTRAGE = 200,
    MOVE_SANDSTORM = 201,
    MOVE_GIGA_DRAIN = 202,
    MOVE_ENDURE = 203,
    MOVE_CHARM = 204,
    MOVE_ROLLOUT = 205,
    MOVE_FALSE_SWIPE = 206,
    MOVE_SWAGGER = 207,
    MOVE_MILK_DRINK = 208,
    MOVE_SPARK = 209,
    MOVE_FURY_CUTTER = 210,
    MOVE_STEEL_WING = 211,
    MOVE_MEAN_LOOK = 212,
    MOVE_ATTRACT = 213,
    MOVE_SLEEP_TALK = 214,
    MOVE_HEAL_BELL = 215,
    MOVE_RETURN = 216,
    MOVE_PRESENT = 217,
    MOVE_FRUSTRATION = 218,
    MOVE_SAFEGUARD = 219,
    MOVE_PAIN_SPLIT = 220,
    MOVE_SACRED_FIRE = 221,
    MOVE_MAGNITUDE = 222,
    MOVE_DYNAMIC_PUNCH = 223,
    MOVE_MEGAHORN = 224,
    MOVE_DRAGON_BREATH = 225,
    MOVE_BATON_PASS = 226,
    MOVE_ENCORE = 227,
    MOVE_PURSUIT = 228,
    MOVE_RAPID_SPIN = 229,
    MOVE_SWEET_SCENT = 230,
    MOVE_IRON_TAIL = 231,
    MOVE_METAL_CLAW = 232,
    MOVE_VITAL_THROW = 233,
    MOVE_MORNING_SUN = 234,
    MOVE_SYNTHESIS = 235,
    MOVE_MOONLIGHT = 236,
    MOVE_HIDDEN_POWER = 237,
    MOVE_CROSS_CHOP = 238,
    MOVE_TWISTER = 239,
    MOVE_RAIN_DANCE = 240,
    MOVE_SUNNY_DAY = 241,
    MOVE_CRUNCH = 242,
    MOVE_MIRROR_COAT = 243,
    MOVE_PSYCH_UP = 244,
    MOVE_EXTREME_SPEED = 245,
    MOVE_ANCIENT_POWER = 246,
    MOVE_SHADOW_BALL = 247,
    MOVE_FUTURE_SIGHT = 248,
    MOVE_ROCK_SMASH = 249,
    MOVE_WHIRLPOOL = 250,
    MOVE_BEAT_UP = 251,
    MOVE_FAKE_OUT = 252,
    MOVE_UPROAR = 253,
    MOVE_STOCKPILE = 254,
    MOVE_SPIT_UP = 255,
    MOVE_SWALLOW = 256,
    MOVE_HEAT_WAVE = 257,
    MOVE_HAIL = 258,
    MOVE_TORMENT = 259,
    MOVE_FLATTER = 260,
    MOVE_WILL_O_WISP = 261,
    MOVE_MEMENTO = 262,
    MOVE_FACADE = 263,
    MOVE_FOCUS_PUNCH = 264,
    MOVE_SMELLING_SALT = 265,
    MOVE_FOLLOW_ME = 266,
    MOVE_NATURE_POWER = 267,
    MOVE_CHARGE = 268,
    MOVE_TAUNT = 269,
    MOVE_HELPING_HAND = 270,
    MOVE_TRICK = 271,
    MOVE_ROLE_PLAY = 272,
    MOVE_WISH = 273,
    MOVE_ASSIST = 274,
    MOVE_INGRAIN = 275,
    MOVE_SUPERPOWER = 276,
    MOVE_MAGIC_COAT = 277,
    MOVE_RECYCLE = 278,
    MOVE_REVENGE = 279,
    MOVE_BRICK_BREAK = 280,
    MOVE_YAWN = 281,
    MOVE_KNOCK_OFF = 282,
    MOVE_ENDEAVOR = 283,
    MOVE_ERUPTION = 284,
    MOVE_SKILL_SWAP = 285,
    MOVE_IMPRISON = 286,
    MOVE_REFRESH = 287,
    MOVE_GRUDGE = 288,
    MOVE_SNATCH = 289,
    MOVE_SECRET_POWER = 290,
    MOVE_DIVE = 291,
    MOVE_ARM_THRUST = 292,
    MOVE_CAMOUFLAGE = 293,
    MOVE_TAIL_GLOW = 294,
    MOVE_LUSTER_PURGE = 295,
    MOVE_MIST_BALL = 296,
    MOVE_FEATHER_DANCE = 297,
    MOVE_TEETER_DANCE = 298,
    MOVE_BLAZE_KICK = 299,
    MOVE_MUD_SPORT = 300,
    MOVE_ICE_BALL = 301,
    MOVE_NEEDLE_ARM = 302,
    MOVE_SLACK_OFF = 303,
    MOVE_HYPER_VOICE = 304,
    MOVE_POISON_FANG = 305,
    MOVE_CRUSH_CLAW = 306,
    MOVE_BLAST_BURN = 307,
    MOVE_HYDRO_CANNON = 308,
    MOVE_METEOR_MASH = 309,
    MOVE_ASTONISH = 310,
    MOVE_WEATHER_BALL = 311,
    MOVE_AROMATHERAPY = 312,
    MOVE_FAKE_TEARS = 313,
    MOVE_AIR_CUTTER = 314,
    MOVE_OVERHEAT = 315,
    MOVE_ODOR_SLEUTH = 316,
    MOVE_ROCK_TOMB = 317,
    MOVE_SILVER_WIND = 318,
    MOVE_METAL_SOUND = 319,
    MOVE_GRASS_WHISTLE = 320,
    MOVE_TICKLE = 321,
    MOVE_COSMIC_POWER = 322,
    MOVE_WATER_SPOUT = 323,
    MOVE_SIGNAL_BEAM = 324,
    MOVE_SHADOW_PUNCH = 325,
    MOVE_EXTRASENSORY = 326,
    MOVE_SKY_UPPERCUT = 327,
    MOVE_SAND_TOMB = 328,
    MOVE_SHEER_COLD = 329,
    MOVE_MUDDY_WATER = 330,
    MOVE_BULLET_SEED = 331,
    MOVE_AERIAL_ACE = 332,
    MOVE_ICICLE_SPEAR = 333,
    MOVE_IRON_DEFENSE = 334,
    MOVE_BLOCK = 335,
    MOVE_HOWL = 336,
    MOVE_DRAGON_CLAW = 337,
    MOVE_FRENZY_PLANT = 338,
    MOVE_BULK_UP = 339,
    MOVE_BOUNCE = 340,
    MOVE_MUD_SHOT = 341,
    MOVE_POISON_TAIL = 342,
    MOVE_COVET = 343,
    MOVE_VOLT_TACKLE = 344,
    MOVE_MAGICAL_LEAF = 345,
    MOVE_WATER_SPORT = 346,
    MOVE_CALM_MIND = 347,
    MOVE_LEAF_BLADE = 348,
    MOVE_DRAGON_DANCE = 349,
    MOVE_ROCK_BLAST = 350,
    MOVE_SHOCK_WAVE = 351,
    MOVE_WATER_PULSE = 352,
    MOVE_DOOM_DESIRE = 353,
    MOVE_PSYCHO_BOOST = 354,
    MOVES_COUNT = 355
};



// Items - indices match Battle Frontier item table (0-62)
// These are used primarily for Battle Factory mechanics
enum : uint16_t {
    ITEM_NONE = 0,
    ITEM_KINGS_ROCK = 1,
    ITEM_SITRUS_BERRY = 2,
    ITEM_ORAN_BERRY = 3,
    ITEM_CHESTO_BERRY = 4,
    ITEM_HARD_STONE = 5,
    ITEM_FOCUS_BAND = 6,
    ITEM_PERSIM_BERRY = 7,
    ITEM_MIRACLE_SEED = 8,
    ITEM_BERRY_JUICE = 9,
    ITEM_MACHO_BRACE = 10,
    ITEM_SILVER_POWDER = 11,
    ITEM_CHERI_BERRY = 12,
    ITEM_BLACK_GLASSES = 13,
    ITEM_BLACK_BELT = 14,
    ITEM_SOUL_DEW = 15,
    ITEM_CHOICE_BAND = 16,
    ITEM_MAGNET = 17,
    ITEM_SILK_SCARF = 18,
    ITEM_WHITE_HERB = 19,
    ITEM_DEEP_SEA_SCALE = 20,
    ITEM_DEEP_SEA_TOOTH = 21,
    ITEM_MYSTIC_WATER = 22,
    ITEM_SHARP_BEAK = 23,
    ITEM_QUICK_CLAW = 24,
    ITEM_LEFTOVERS = 25,
    ITEM_RAWST_BERRY = 26,
    ITEM_LIGHT_BALL = 27,
    ITEM_POISON_BARB = 28,
    ITEM_NEVER_MELT_ICE = 29,
    ITEM_ASPEAR_BERRY = 30,
    ITEM_SPELL_TAG = 31,
    ITEM_BRIGHT_POWDER = 32,
    ITEM_LEPPA_BERRY = 33,
    ITEM_SCOPE_LENS = 34,
    ITEM_TWISTED_SPOON = 35,
    ITEM_METAL_COAT = 36,
    ITEM_MENTAL_HERB = 37,
    ITEM_CHARCOAL = 38,
    ITEM_PECHA_BERRY = 39,
    ITEM_SOFT_SAND = 40,
    ITEM_LUM_BERRY = 41,
    ITEM_DRAGON_SCALE = 42,
    ITEM_DRAGON_FANG = 43,
    ITEM_IAPAPA_BERRY = 44,
    ITEM_WIKI_BERRY = 45,
    ITEM_SEA_INCENSE = 46,
    ITEM_SHELL_BELL = 47,
    ITEM_SALAC_BERRY = 48,
    ITEM_LANSAT_BERRY = 49,
    ITEM_APICOT_BERRY = 50,
    ITEM_STARF_BERRY = 51,
    ITEM_LIECHI_BERRY = 52,
    ITEM_GANLON_BERRY = 53,
    ITEM_PETAYA_BERRY = 54,
    ITEM_FIGY_BERRY = 55,
    ITEM_AGUAV_BERRY = 56,
    ITEM_MAGO_BERRY = 57,
    ITEM_LAX_INCENSE = 58,
    ITEM_COUNT = 63  // ~59-62 are duplicates in the table, not used
};


// Abilities (auto-generated)
enum : uint16_t {
    ABILITY_AIR_LOCK = 0,
    ABILITY_ARENA_TRAP = 1,
    ABILITY_BATTLE_ARMOR = 2,
    ABILITY_BLAZE = 3,
    ABILITY_CHLOROPHYLL = 4,
    ABILITY_CLEAR_BODY = 5,
    ABILITY_CLOUD_NINE = 6,
    ABILITY_COLOR_CHANGE = 7,
    ABILITY_COMPOUND_EYES = 8,
    ABILITY_CUTE_CHARM = 9,
    ABILITY_DAMP = 10,
    ABILITY_DRIZZLE = 11,
    ABILITY_DROUGHT = 12,
    ABILITY_EARLY_BIRD = 13,
    ABILITY_EFFECT_SPORE = 14,
    ABILITY_FLAME_BODY = 15,
    ABILITY_FLASH_FIRE = 16,
    ABILITY_FORECAST = 17,
    ABILITY_GUTS = 18,
    ABILITY_HUGE_POWER = 19,
    ABILITY_HUSTLE = 20,
    ABILITY_HYPER_CUTTER = 21,
    ABILITY_ILLUMINATE = 22,
    ABILITY_IMMUNITY = 23,
    ABILITY_INNER_FOCUS = 24,
    ABILITY_INSOMNIA = 25,
    ABILITY_INTIMIDATE = 26,
    ABILITY_KEEN_EYE = 27,
    ABILITY_LEVITATE = 28,
    ABILITY_LIGHTNING_ROD = 29,
    ABILITY_LIMBER = 30,
    ABILITY_LIQUID_OOZE = 31,
    ABILITY_MAGMA_ARMOR = 32,
    ABILITY_MAGNET_PULL = 33,
    ABILITY_MARVEL_SCALE = 34,
    ABILITY_MINUS = 35,
    ABILITY_NATURAL_CURE = 36,
    ABILITY_NONE = 37,
    ABILITY_OBLIVIOUS = 38,
    ABILITY_OVERGROW = 39,
    ABILITY_OWN_TEMPO = 40,
    ABILITY_PICKUP = 41,
    ABILITY_PLUS = 42,
    ABILITY_POISON_POINT = 43,
    ABILITY_PRESSURE = 44,
    ABILITY_PURE_POWER = 45,
    ABILITY_RAIN_DISH = 46,
    ABILITY_ROCK_HEAD = 47,
    ABILITY_ROUGH_SKIN = 48,
    ABILITY_RUN_AWAY = 49,
    ABILITY_SAND_STREAM = 50,
    ABILITY_SAND_VEIL = 51,
    ABILITY_SERENE_GRACE = 52,
    ABILITY_SHADOW_TAG = 53,
    ABILITY_SHED_SKIN = 54,
    ABILITY_SHELL_ARMOR = 55,
    ABILITY_SHIELD_DUST = 56,
    ABILITY_SOUNDPROOF = 57,
    ABILITY_SPEED_BOOST = 58,
    ABILITY_STATIC = 59,
    ABILITY_STENCH = 60,
    ABILITY_STICKY_HOLD = 61,
    ABILITY_STURDY = 62,
    ABILITY_SUCTION_CUPS = 63,
    ABILITY_SWARM = 64,
    ABILITY_SWIFT_SWIM = 65,
    ABILITY_SYNCHRONIZE = 66,
    ABILITY_THICK_FAT = 67,
    ABILITY_TORRENT = 68,
    ABILITY_TRACE = 69,
    ABILITY_TRUANT = 70,
    ABILITY_VITAL_SPIRIT = 71,
    ABILITY_VOLT_ABSORB = 72,
    ABILITY_WATER_ABSORB = 73,
    ABILITY_WATER_VEIL = 74,
    ABILITY_WHITE_SMOKE = 75,
    ABILITY_WONDER_GUARD = 76,
    ABILITY_COUNT = 77
};

constexpr uint8_t EV_HP = 0x01;
constexpr uint8_t EV_ATTACK = 0x02;
constexpr uint8_t EV_DEFENSE = 0x04;
constexpr uint8_t EV_SPEED = 0x08;
constexpr uint8_t EV_SP_ATK = 0x10;
constexpr uint8_t EV_SP_DEF = 0x20;

constexpr int MAX_PARTY_SIZE = 6;
constexpr int MAX_MOVES = 4;
constexpr int MAX_LEVEL = 100;

constexpr int STAT_STAGE_NUMERATORS[] = {2, 2, 2, 2, 2, 2, 2, 3, 4, 5, 6, 7, 8};
constexpr int STAT_STAGE_DENOMINATORS[] = {8, 7, 6, 5, 4, 3, 2, 2, 2, 2, 2, 2, 2};

}  // namespace pkmn
// Accuracy stage modifiers (index 0-12 for stages -6 to +6)
constexpr int ACC_STAGE_NUMERATORS[] = {33, 36, 43, 50, 60, 75, 100, 133, 166, 200, 250, 266, 300};
constexpr int ACC_STAGE_DENOMINATORS[] = {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100};

// Critical hit chances (Gen 3: 1/16, 1/8, 1/4, 1/3, 1/2)  
constexpr int CRIT_CHANCE_NUMERATORS[] = {1, 1, 1, 1, 1};
constexpr int CRIT_CHANCE_DENOMINATORS[] = {16, 8, 4, 3, 2};

// ============================================================================
// Battle AI Constants
// ============================================================================

// Battlers
#define AI_TARGET 0
#define AI_USER 1
#define AI_TARGET_PARTNER 2
#define AI_USER_PARTNER 3

// Get Type Command
#define AI_TYPE1_TARGET 0
#define AI_TYPE1_USER 1
#define AI_TYPE2_TARGET 2
#define AI_TYPE2_USER 3
#define AI_TYPE_MOVE 4

// Type Effectiveness
#define AI_EFFECTIVENESS_x4     160
#define AI_EFFECTIVENESS_x2     80
#define AI_EFFECTIVENESS_x1     40
#define AI_EFFECTIVENESS_x0_5   20
#define AI_EFFECTIVENESS_x0_25  10
#define AI_EFFECTIVENESS_x0     0

// AI Weather
#define AI_WEATHER_NONE 0xFFFFFFFF
#define AI_WEATHER_SUN 0
#define AI_WEATHER_RAIN 1
#define AI_WEATHER_SANDSTORM 2
#define AI_WEATHER_HAIL 3

// Power checks
#define MOVE_POWER_OTHER        0
#define MOVE_NOT_MOST_POWERFUL  1
#define MOVE_MOST_POWERFUL      2

// Script Flags
#define AI_SCRIPT_CHECK_BAD_MOVE        (1 << 0)
#define AI_SCRIPT_TRY_TO_FAINT          (1 << 1)
#define AI_SCRIPT_CHECK_VIABILITY       (1 << 2)
#define AI_SCRIPT_SETUP_FIRST_TURN      (1 << 3)
#define AI_SCRIPT_RISKY                 (1 << 4)
#define AI_SCRIPT_PREFER_POWER_EXTREMES (1 << 5)
#define AI_SCRIPT_PREFER_BATON_PASS     (1 << 6)
#define AI_SCRIPT_DOUBLE_BATTLE         (1 << 7)
#define AI_SCRIPT_HP_AWARE              (1 << 8)
#define AI_SCRIPT_TRY_SUNNY_DAY_START   (1 << 9)
#define AI_SCRIPT_ROAMING               (1 << 29)
#define AI_SCRIPT_SAFARI                (1 << 30)
#define AI_SCRIPT_FIRST_BATTLE          (1 << 31)

// AI Actions
#define AI_ACTION_DONE          (1 << 0)
#define AI_ACTION_FLEE          (1 << 1)
#define AI_ACTION_WATCH         (1 << 2)
#define AI_ACTION_DO_NOT_ATTACK (1 << 3)

// Status Constants
// Non-volatile status conditions
#define STATUS1_NONE             0
#define STATUS1_SLEEP            (1 << 0 | 1 << 1 | 1 << 2) // First 3 bits (Number of turns to sleep)
#define STATUS1_SLEEP_TURN(num)  ((num) << 0)
#define STATUS1_POISON           (1 << 3)
#define STATUS1_BURN             (1 << 4)
#define STATUS1_FREEZE           (1 << 5)
#define STATUS1_PARALYSIS        (1 << 6)
#define STATUS1_TOXIC_POISON     (1 << 7)
#define STATUS1_TOXIC_COUNTER    (1 << 8 | 1 << 9 | 1 << 10 | 1 << 11)
#define STATUS1_TOXIC_TURN(num)  ((num) << 8)
#define STATUS1_PSN_ANY          (STATUS1_POISON | STATUS1_TOXIC_POISON)
#define STATUS1_ANY              (STATUS1_SLEEP | STATUS1_POISON | STATUS1_BURN | STATUS1_FREEZE | STATUS1_PARALYSIS | STATUS1_TOXIC_POISON)

// Volatile status ailments
#define STATUS2_CONFUSION             (1 << 0 | 1 << 1 | 1 << 2)
#define STATUS2_CONFUSION_TURN(num)   ((num) << 0)
#define STATUS2_FLINCHED              (1 << 3)
#define STATUS2_UPROAR                (1 << 4 | 1 << 5 | 1 << 6)
#define STATUS2_UPROAR_TURN(num)      ((num) << 4)
#define STATUS2_UNUSED                (1 << 7)
#define STATUS2_BIDE                  (1 << 8 | 1 << 9)
#define STATUS2_BIDE_TURN(num)        (((num) << 8) & STATUS2_BIDE)
#define STATUS2_LOCK_CONFUSE          (1 << 10 | 1 << 11)
#define STATUS2_LOCK_CONFUSE_TURN(num)((num) << 10)
#define STATUS2_MULTIPLETURNS         (1 << 12)
#define STATUS2_WRAPPED               (1 << 13 | 1 << 14 | 1 << 15)
#define STATUS2_WRAPPED_TURN(num)     ((num) << 13)
#define STATUS2_INFATUATION           (1 << 16 | 1 << 17 | 1 << 18 | 1 << 19)
#define STATUS2_INFATUATED_WITH(battler) ((1 << battler) << 16)
#define STATUS2_FOCUS_ENERGY          (1 << 20)
#define STATUS2_TRANSFORMED           (1 << 21)
#define STATUS2_RECHARGE              (1 << 22)
#define STATUS2_RAGE                  (1 << 23)
#define STATUS2_SUBSTITUTE            (1 << 24)
#define STATUS2_DESTINY_BOND          (1 << 25)
#define STATUS2_ESCAPE_PREVENTION     (1 << 26)
#define STATUS2_NIGHTMARE             (1 << 27)
#define STATUS2_CURSED                (1 << 28)
#define STATUS2_FORESIGHT             (1 << 29)
#define STATUS2_DEFENSE_CURL          (1 << 30)
#define STATUS2_TORMENT               (1 << 31)

// Status 3
#define STATUS3_LEECHSEED_BATTLER       (1 << 0 | 1 << 1)
#define STATUS3_LEECHSEED               (1 << 2)
#define STATUS3_ALWAYS_HITS             (1 << 3 | 1 << 4)
#define STATUS3_ALWAYS_HITS_TURN(num)   (((num) << 3) & STATUS3_ALWAYS_HITS)
#define STATUS3_PERISH_SONG             (1 << 5)
#define STATUS3_ON_AIR                  (1 << 6)
#define STATUS3_UNDERGROUND             (1 << 7)
#define STATUS3_MINIMIZED               (1 << 8)
#define STATUS3_CHARGED_UP              (1 << 9)
#define STATUS3_ROOTED                  (1 << 10)
#define STATUS3_YAWN                    (1 << 11 | 1 << 12)
#define STATUS3_YAWN_TURN(num)          (((num) << 11) & STATUS3_YAWN)
#define STATUS3_IMPRISONED_OTHERS       (1 << 13)
#define STATUS3_GRUDGE                  (1 << 14)
#define STATUS3_CANT_SCORE_A_CRIT       (1 << 15)
#define STATUS3_MUDSPORT                (1 << 16)
#define STATUS3_WATERSPORT              (1 << 17)
#define STATUS3_UNDERWATER              (1 << 18)
#define STATUS3_INTIMIDATE_POKES        (1 << 19)
#define STATUS3_TRACE                   (1 << 20)
#define STATUS3_SEMI_INVULNERABLE       (STATUS3_UNDERGROUND | STATUS3_ON_AIR | STATUS3_UNDERWATER)

// Side Status
#define SIDE_STATUS_REFLECT          (1 << 0)
#define SIDE_STATUS_LIGHTSCREEN      (1 << 1)
#define SIDE_STATUS_X4               (1 << 2)
#define SIDE_STATUS_SPIKES           (1 << 4)
#define SIDE_STATUS_SAFEGUARD        (1 << 5)
#define SIDE_STATUS_FUTUREATTACK     (1 << 6)
#define SIDE_STATUS_MIST             (1 << 8)
#define SIDE_STATUS_SPIKES_DAMAGED   (1 << 9)

// AI Script Mappings
// Types
#define TYPE_NORMAL   0
#define TYPE_FIGHTING 1
#define TYPE_FLYING   2
#define TYPE_POISON   3
#define TYPE_GROUND   4
#define TYPE_ROCK     5
#define TYPE_BUG      6
#define TYPE_GHOST    7
#define TYPE_STEEL    8
#define TYPE_MYSTERY  9
#define TYPE_FIRE     10
#define TYPE_WATER    11
#define TYPE_GRASS    12
#define TYPE_ELECTRIC 13
#define TYPE_PSYCHIC  14
#define TYPE_ICE      15
#define TYPE_DRAGON   16
#define TYPE_DARK     17

// Stats (BattleStat mapping)
#define STAT_ATK 0
#define STAT_DEF 1
#define STAT_SPATK 2
#define STAT_SPDEF 3
#define STAT_SPEED 4
#define STAT_ACC 5
#define STAT_EVASION 6

#define DEFAULT_STAT_STAGE 6
#define MAX_STAT_STAGE 12
#define MIN_STAT_STAGE 0

// Gender Constants
#define MON_MALE       0x00
#define MON_FEMALE     0xFE
#define MON_GENDERLESS 0xFF

// Effects (Auto-generated from types.hpp)
#define EFFECT_ABSORB 0
#define EFFECT_ACCURACY_DOWN 1
#define EFFECT_ACCURACY_DOWN_HIT 2
#define EFFECT_ALL_STATS_UP_HIT 3
#define EFFECT_ALWAYS_HIT 4
#define EFFECT_ASSIST 5
#define EFFECT_ATTACK_DOWN 6
#define EFFECT_ATTACK_DOWN_2 7
#define EFFECT_ATTACK_DOWN_HIT 8
#define EFFECT_ATTACK_UP 9
#define EFFECT_ATTACK_UP_2 10
#define EFFECT_ATTACK_UP_HIT 11
#define EFFECT_ATTRACT 12
#define EFFECT_BATON_PASS 13
#define EFFECT_BEAT_UP 14
#define EFFECT_BELLY_DRUM 15
#define EFFECT_BIDE 16
#define EFFECT_BLAZE_KICK 17
#define EFFECT_BRICK_BREAK 18
#define EFFECT_BULK_UP 19
#define EFFECT_BURN_HIT 20
#define EFFECT_CALM_MIND 21
#define EFFECT_CAMOUFLAGE 22
#define EFFECT_CHARGE 23
#define EFFECT_CONFUSE 24
#define EFFECT_CONFUSE_HIT 25
#define EFFECT_CONVERSION 26
#define EFFECT_CONVERSION_2 27
#define EFFECT_COSMIC_POWER 28
#define EFFECT_COUNTER 29
#define EFFECT_CURSE 30
#define EFFECT_DEFENSE_CURL 31
#define EFFECT_DEFENSE_DOWN 32
#define EFFECT_DEFENSE_DOWN_2 33
#define EFFECT_DEFENSE_DOWN_HIT 34
#define EFFECT_DEFENSE_UP 35
#define EFFECT_DEFENSE_UP_2 36
#define EFFECT_DEFENSE_UP_HIT 37
#define EFFECT_DESTINY_BOND 38
#define EFFECT_DISABLE 39
#define EFFECT_DOUBLE_EDGE 40
#define EFFECT_DOUBLE_HIT 41
#define EFFECT_DRAGON_DANCE 42
#define EFFECT_DRAGON_RAGE 43
#define EFFECT_DREAM_EATER 44
#define EFFECT_EARTHQUAKE 45
#define EFFECT_ENCORE 46
#define EFFECT_ENDEAVOR 47
#define EFFECT_ENDURE 48
#define EFFECT_ERUPTION 49
#define EFFECT_EVASION_DOWN 50
#define EFFECT_EVASION_UP 51
#define EFFECT_EXPLOSION 52
#define EFFECT_FACADE 53
#define EFFECT_FAKE_OUT 54
#define EFFECT_FALSE_SWIPE 55
#define EFFECT_FLAIL 56
#define EFFECT_FLATTER 57
#define EFFECT_FLINCH_HIT 58
#define EFFECT_FLINCH_MINIMIZE_HIT 59
#define EFFECT_FOCUS_ENERGY 60
#define EFFECT_FOCUS_PUNCH 61
#define EFFECT_FOLLOW_ME 62
#define EFFECT_FORESIGHT 63
#define EFFECT_FREEZE_HIT 64
#define EFFECT_FRUSTRATION 65
#define EFFECT_FURY_CUTTER 66
#define EFFECT_FUTURE_SIGHT 67
#define EFFECT_GRUDGE 68
#define EFFECT_GUST 69
#define EFFECT_HAIL 70
#define EFFECT_HAZE 71
#define EFFECT_HEAL_BELL 72
#define EFFECT_HELPING_HAND 73
#define EFFECT_HIDDEN_POWER 74
#define EFFECT_HIGH_CRITICAL 75
#define EFFECT_HIT 76
#define EFFECT_IMPRISON 77
#define EFFECT_INGRAIN 78
#define EFFECT_KNOCK_OFF 79
#define EFFECT_LEECH_SEED 80
#define EFFECT_LEVEL_DAMAGE 81
#define EFFECT_LIGHT_SCREEN 82
#define EFFECT_LOCK_ON 83
#define EFFECT_LOW_KICK 84
#define EFFECT_MAGIC_COAT 85
#define EFFECT_MAGNITUDE 86
#define EFFECT_MEAN_LOOK 87
#define EFFECT_MEMENTO 88
#define EFFECT_METRONOME 89
#define EFFECT_MIMIC 90
#define EFFECT_MINIMIZE 91
#define EFFECT_MIRROR_COAT 92
#define EFFECT_MIRROR_MOVE 93
#define EFFECT_MIST 94
#define EFFECT_MOONLIGHT 95
#define EFFECT_MORNING_SUN 96
#define EFFECT_MUD_SPORT 97
#define EFFECT_MULTI_HIT 98
#define EFFECT_NATURE_POWER 99
#define EFFECT_NIGHTMARE 100
#define EFFECT_OHKO 101
#define EFFECT_OVERHEAT 102
#define EFFECT_PAIN_SPLIT 103
#define EFFECT_PARALYZE 104
#define EFFECT_PARALYZE_HIT 105
#define EFFECT_PAY_DAY 106
#define EFFECT_PERISH_SONG 107
#define EFFECT_POISON 108
#define EFFECT_POISON_FANG 109
#define EFFECT_POISON_HIT 110
#define EFFECT_POISON_TAIL 111
#define EFFECT_PRESENT 112
#define EFFECT_PROTECT 113
#define EFFECT_PSYCH_UP 114
#define EFFECT_PSYWAVE 115
#define EFFECT_PURSUIT 116
#define EFFECT_QUICK_ATTACK 117
#define EFFECT_RAGE 118
#define EFFECT_RAIN_DANCE 119
#define EFFECT_RAMPAGE 120
#define EFFECT_RAPID_SPIN 121
#define EFFECT_RAZOR_WIND 122
#define EFFECT_RECHARGE 123
#define EFFECT_RECOIL 124
#define EFFECT_RECOIL_IF_MISS 125
#define EFFECT_RECYCLE 126
#define EFFECT_REFLECT 127
#define EFFECT_REFRESH 128
#define EFFECT_REST 129
#define EFFECT_RESTORE_HP 130
#define EFFECT_RETURN 131
#define EFFECT_REVENGE 132
#define EFFECT_ROAR 133
#define EFFECT_ROLE_PLAY 134
#define EFFECT_ROLLOUT 135
#define EFFECT_SAFEGUARD 136
#define EFFECT_SANDSTORM 137
#define EFFECT_SECRET_POWER 138
#define EFFECT_SEMI_INVULNERABLE 139
#define EFFECT_SKETCH 140
#define EFFECT_SKILL_SWAP 141
#define EFFECT_SKULL_BASH 142
#define EFFECT_SKY_ATTACK 143
#define EFFECT_SKY_UPPERCUT 144
#define EFFECT_SLEEP 145
#define EFFECT_SLEEP_TALK 146
#define EFFECT_SMELLINGSALT 147
#define EFFECT_SNATCH 148
#define EFFECT_SNORE 149
#define EFFECT_SOFTBOILED 150
#define EFFECT_SOLAR_BEAM 151
#define EFFECT_SONICBOOM 152
#define EFFECT_SPECIAL_ATTACK_DOWN_HIT 153
#define EFFECT_SPECIAL_ATTACK_UP 154
#define EFFECT_SPECIAL_ATTACK_UP_2 155
#define EFFECT_SPECIAL_DEFENSE_UP 199 // Missing in types.hpp
#define EFFECT_SPEED_UP 206
#define EFFECT_ACCURACY_UP 207
#define EFFECT_SPECIAL_ATTACK_DOWN 208
#define EFFECT_SPECIAL_ATTACK_DOWN_2 200
#define EFFECT_ACCURACY_DOWN_2 201
#define EFFECT_EVASION_DOWN_2 202
#define EFFECT_SPECIAL_DEFENSE_DOWN 203
#define EFFECT_ACCURACY_UP_2 204
#define EFFECT_EVASION_UP_2 205
#define EFFECT_SPECIAL_DEFENSE_DOWN_2 156
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT 157
#define EFFECT_SPECIAL_DEFENSE_UP_2 158
#define EFFECT_SPEED_DOWN 159
#define EFFECT_SPEED_DOWN_2 160
#define EFFECT_SPEED_DOWN_HIT 161
#define EFFECT_SPEED_UP_2 162
#define EFFECT_SPIKES 163
#define EFFECT_SPITE 164
#define EFFECT_SPIT_UP 165
#define EFFECT_SPLASH 166
#define EFFECT_STOCKPILE 167
#define EFFECT_SUBSTITUTE 168
#define EFFECT_SUNNY_DAY 169
#define EFFECT_SUPERPOWER 170
#define EFFECT_SUPER_FANG 171
#define EFFECT_SWAGGER 172
#define EFFECT_SWALLOW 173
#define EFFECT_SYNTHESIS 174
#define EFFECT_TAUNT 175
#define EFFECT_TEETER_DANCE 176
#define EFFECT_TELEPORT 177
#define EFFECT_THAW_HIT 178
#define EFFECT_THIEF 179
#define EFFECT_THUNDER 180
#define EFFECT_TICKLE 181
#define EFFECT_TORMENT 182
#define EFFECT_TOXIC 183
#define EFFECT_TRANSFORM 184
#define EFFECT_TRAP 185
#define EFFECT_TRICK 186
#define EFFECT_TRIPLE_KICK 187
#define EFFECT_TRI_ATTACK 188
#define EFFECT_TWINEEDLE 189
#define EFFECT_TWISTER 190
#define EFFECT_UPROAR 191
#define EFFECT_VITAL_THROW 192
#define EFFECT_WATER_SPORT 193
#define EFFECT_WEATHER_BALL 194
#define EFFECT_WILL_O_WISP 195
#define EFFECT_WISH 196
#define EFFECT_YAWN 197
#define EFFECT_COUNT 198

