// GENERATED by scripts/extract_game_data.py from pokeemerald.elf. Do not edit.
#pragma once

#include <cstdint>

namespace pkmn {

extern const uint16_t FACTORY_RENTAL_RANGES[16][2];  // [challenge + 8*openLevel]
extern const uint8_t FACTORY_FIXED_IVS[9][2];          // [challenge][useHigherIV]
extern const uint8_t FACTORY_STYLE_REQUIRED_COUNTS[7];
extern const uint16_t* const FACTORY_STYLE_MOVES[7];  // MOVE_NONE terminated
extern const uint16_t FRONTIER_TRAINER_RANGES[8][2];
extern const uint16_t FRONTIER_TRAINER_RANGES_HARD[8][2];
extern const uint16_t NUM_FRONTIER_TRAINERS;
extern const uint8_t FRONTIER_BRAIN_STREAK_APPEARANCES[7][4];
extern const uint16_t CRITICAL_HIT_CHANCE[5];

}  // namespace pkmn
