// GENERATED by scripts/extract_game_data.py from pokeemerald.elf. Do not edit.
#include "game_tables.hpp"

namespace pkmn {

// battle_factory.c
const uint16_t FACTORY_RENTAL_RANGES[16][2] = {{110, 199}, {162, 266}, {267, 371}, {372, 467}, {468, 563}, {564, 659}, {660, 755}, {372, 849}, {372, 467}, {468, 563}, {564, 659}, {660, 755}, {372, 881}, {372, 881}, {372, 881}, {372, 881}};
// Last row is the out-of-bounds read at challengeNum 8 (vanilla GetFactoryMonFixedIV bug).
const uint8_t FACTORY_FIXED_IVS[9][2] = {{3, 6}, {6, 9}, {9, 12}, {12, 15}, {15, 18}, {21, 31}, {31, 31}, {31, 31}, {110, 0}};
const uint8_t FACTORY_STYLE_REQUIRED_COUNTS[7] = {3, 3, 3, 2, 2, 2, 2};
static const uint16_t STYLE_MOVES_0[] = {14, 74, 96, 97, 104, 106, 107, 110, 111, 112, 116, 133, 151, 159, 160, 176, 187, 244, 268, 289, 294, 322, 334, 336, 339, 347, 349, 0};
static const uint16_t STYLE_MOVES_1[] = {47, 48, 50, 73, 77, 78, 79, 86, 92, 95, 109, 137, 139, 142, 147, 169, 186, 191, 207, 212, 213, 227, 259, 260, 261, 269, 281, 286, 289, 298, 320, 335, 0};
static const uint16_t STYLE_MOVES_2[] = {54, 105, 113, 114, 115, 135, 156, 182, 197, 203, 208, 215, 219, 226, 234, 235, 236, 256, 273, 275, 277, 278, 287, 300, 303, 312, 346, 0};
static const uint16_t STYLE_MOVES_3[] = {12, 32, 38, 63, 68, 90, 117, 120, 143, 153, 175, 179, 194, 195, 220, 243, 262, 288, 263, 264, 307, 308, 315, 338, 354, 344, 0};
static const uint16_t STYLE_MOVES_4[] = {28, 39, 43, 45, 81, 103, 108, 134, 148, 178, 180, 184, 204, 282, 230, 297, 313, 319, 321, 0};
static const uint16_t STYLE_MOVES_5[] = {102, 118, 119, 144, 164, 166, 174, 217, 266, 271, 272, 274, 285, 293, 0};
static const uint16_t STYLE_MOVES_6[] = {201, 240, 241, 258, 311, 0};
const uint16_t* const FACTORY_STYLE_MOVES[7] = {STYLE_MOVES_0, STYLE_MOVES_1, STYLE_MOVES_2, STYLE_MOVES_3, STYLE_MOVES_4, STYLE_MOVES_5, STYLE_MOVES_6};

// battle_tower.c
const uint16_t FRONTIER_TRAINER_RANGES[8][2] = {{0, 99}, {80, 119}, {100, 139}, {120, 159}, {140, 179}, {160, 199}, {180, 219}, {200, 299}};
const uint16_t FRONTIER_TRAINER_RANGES_HARD[8][2] = {{100, 119}, {120, 139}, {140, 159}, {160, 179}, {180, 199}, {200, 219}, {220, 239}, {200, 299}};
const uint16_t NUM_FRONTIER_TRAINERS = 300;

// frontier_util.c
const uint8_t FRONTIER_BRAIN_STREAK_APPEARANCES[7][4] = {{35, 70, 35, 1}, {4, 9, 5, 0}, {21, 42, 21, 1}, {28, 56, 28, 1}, {21, 42, 21, 1}, {28, 140, 56, 1}, {21, 70, 35, 0}};

// battle_script_commands.c
const uint16_t CRITICAL_HIT_CHANCE[5] = {16, 8, 4, 3, 2};

}  // namespace pkmn
