// GENERATED by scripts/extract_game_data.py from pokeemerald.elf. Do not edit.
#include "data.hpp"

namespace pkmn {

// gTypeEffectiveness, in game order. {atk, def, multiplier(x10)};
// atk == TYPE_FORESIGHT (0xFE) separates the Foresight-ignorable entries, 0xFF ends the table.
const TypeEffectivenessEntry TYPE_EFFECTIVENESS[112] = {{0, 5, 5}, {0, 8, 5}, {10, 10, 5}, {10, 11, 5}, {10, 12, 20}, {10, 15, 20}, {10, 6, 20}, {10, 5, 5}, {10, 16, 5}, {10, 8, 20}, {11, 10, 20}, {11, 11, 5}, {11, 12, 5}, {11, 4, 20}, {11, 5, 20}, {11, 16, 5}, {13, 11, 20}, {13, 13, 5}, {13, 12, 5}, {13, 4, 0}, {13, 2, 20}, {13, 16, 5}, {12, 10, 5}, {12, 11, 20}, {12, 12, 5}, {12, 3, 5}, {12, 4, 20}, {12, 2, 5}, {12, 6, 5}, {12, 5, 20}, {12, 16, 5}, {12, 8, 5}, {15, 11, 5}, {15, 12, 20}, {15, 15, 5}, {15, 4, 20}, {15, 2, 20}, {15, 16, 20}, {15, 8, 5}, {15, 10, 5}, {1, 0, 20}, {1, 15, 20}, {1, 3, 5}, {1, 2, 5}, {1, 14, 5}, {1, 6, 5}, {1, 5, 20}, {1, 17, 20}, {1, 8, 20}, {3, 12, 20}, {3, 3, 5}, {3, 4, 5}, {3, 5, 5}, {3, 7, 5}, {3, 8, 0}, {4, 10, 20}, {4, 13, 20}, {4, 12, 5}, {4, 3, 20}, {4, 2, 0}, {4, 6, 5}, {4, 5, 20}, {4, 8, 20}, {2, 13, 5}, {2, 12, 20}, {2, 1, 20}, {2, 6, 20}, {2, 5, 5}, {2, 8, 5}, {14, 1, 20}, {14, 3, 20}, {14, 14, 5}, {14, 17, 0}, {14, 8, 5}, {6, 10, 5}, {6, 12, 20}, {6, 1, 5}, {6, 3, 5}, {6, 2, 5}, {6, 14, 20}, {6, 7, 5}, {6, 17, 20}, {6, 8, 5}, {5, 10, 20}, {5, 15, 20}, {5, 1, 5}, {5, 4, 5}, {5, 2, 20}, {5, 6, 20}, {5, 8, 5}, {7, 0, 0}, {7, 14, 20}, {7, 17, 5}, {7, 8, 5}, {7, 7, 20}, {16, 16, 20}, {16, 8, 5}, {17, 1, 5}, {17, 14, 20}, {17, 7, 20}, {17, 17, 5}, {17, 8, 5}, {8, 10, 5}, {8, 11, 5}, {8, 13, 5}, {8, 15, 20}, {8, 5, 20}, {8, 8, 5}, {254, 254, 0}, {0, 7, 0}, {1, 7, 0}, {255, 255, 0}};
const size_t TYPE_EFFECTIVENESS_COUNT = 112;

// gNatureStatTable: [nature][Atk, Def, Spe, SpA, SpD] -> +1 / -1 / 0
static const int8_t NATURE_STAT_TABLE[25][5] = {
    {0, 0, 0, 0, 0},
    {1, -1, 0, 0, 0},
    {1, 0, -1, 0, 0},
    {1, 0, 0, -1, 0},
    {1, 0, 0, 0, -1},
    {-1, 1, 0, 0, 0},
    {0, 0, 0, 0, 0},
    {0, 1, -1, 0, 0},
    {0, 1, 0, -1, 0},
    {0, 1, 0, 0, -1},
    {-1, 0, 1, 0, 0},
    {0, -1, 1, 0, 0},
    {0, 0, 0, 0, 0},
    {0, 0, 1, -1, 0},
    {0, 0, 1, 0, -1},
    {-1, 0, 0, 1, 0},
    {0, -1, 0, 1, 0},
    {0, 0, -1, 1, 0},
    {0, 0, 0, 0, 0},
    {0, 0, 0, 1, -1},
    {-1, 0, 0, 0, 1},
    {0, -1, 0, 0, 1},
    {0, 0, -1, 0, 1},
    {0, 0, 0, -1, 1},
    {0, 0, 0, 0, 0}
};

// gStatStageRatios: numerator/denominator for stages -6..+6
const uint8_t STAT_STAGE_RATIOS[13][2] = {{10, 40}, {10, 35}, {10, 30}, {10, 25}, {10, 20}, {10, 15}, {10, 10}, {15, 10}, {20, 10}, {25, 10}, {30, 10}, {35, 10}, {40, 10}};

int getTypeEffectiveness(Type attackType, Type defendType) {
    for (size_t i = 0; i < TYPE_EFFECTIVENESS_COUNT; i++) {
        const auto& e = TYPE_EFFECTIVENESS[i];
        if (e.attacker == TYPE_ENDTABLE) break;
        if (e.attacker == static_cast<uint8_t>(attackType) && e.defender == static_cast<uint8_t>(defendType))
            return e.multiplier * 10;  // x10 multiplier -> x100 scale
    }
    return 100;
}

int getTypeEffectivenessDual(Type attackType, Type defType1, Type defType2) {
    int eff1 = getTypeEffectiveness(attackType, defType1);
    if (defType1 == defType2) return eff1;
    return eff1 * getTypeEffectiveness(attackType, defType2) / 100;
}

int getNatureModifier(Nature nature, Stat stat) {
    if (stat == Stat::HP) return 100;
    return 100 + 10 * NATURE_STAT_TABLE[static_cast<int>(nature)][static_cast<int>(stat) - 1];
}

void calculateEVsFromSpread(uint8_t evSpread, uint8_t* outEVs) {
    // CreateMonWithEVSpreadNatureOTID: MAX_TOTAL_EVS / number of flagged stats
    int count = 0;
    for (int i = 0; i < 6; i++)
        if (evSpread & (1 << i)) count++;
    int amount = count ? 510 / count : 0;
    for (int i = 0; i < 6; i++)
        outEVs[i] = (evSpread & (1 << i)) ? static_cast<uint8_t>(amount) : 0;
}

}  // namespace pkmn
